"""Offline sanity check for the OG-IPF stack (PROJECT_STATE §7.20).

Runs without GPU, without VTM, without YOLO. The tests cover the
mathematical invariants of the new method:

1. ``occupancy.compute_occupancy_utility`` reduces to zero when there
   are no boxes, and to a sane scalar field when there is one big box.
2. ``A^obj`` correctly emphasises **small** objects (the central
   failure mode the OG-IPF is meant to fix).
3. ``min_protection_floor`` schedules δ_min monotonically over Q_b
   inside the [floor, ceil] band.
4. ``apply_min_object_protection`` is idempotent and never *raises*
   δ for any CTU (it can only push it down).
5. ``end_to_end_og_a_plus`` produces a continuous map whose
   K-weighted rate ratio is ≈ 1.0 (rate-neutral by construction).
6. ``compute_og_diagnostics`` reports ``object_protection_violation
   ≤ 5 %`` on a synthetic frame where the constraint is met.
7. ``ObjectBox.from_dict`` accepts all three legitimate dict shapes
   (Phase 1 ObjectState, simple ``{x, y, w, h}``, and YOLO ``xyxy``).
8. End-to-end smoke: ``apply_liteqp_model --mode og_a_plus`` produces
   ``qp_vtm_delta_QP{n}/`` with one map per (QP, frame) and writes
   a non-empty ``og_diagnostics_summary.csv`` for a 5-frame fake
   sequence (needs no YOLO — boxes JSON files are pre-generated by
   the test).

Run::

    PYTHONPATH=src python scripts/sanity_check_og_ipf.py

Exit 0 on success.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except AttributeError:
    pass

HERE = Path(__file__).resolve().parents[1]
SRC  = HERE / "src"
sys.path.insert(0, str(SRC))

import numpy as np  # noqa: E402  (after sys.path manipulation)

from phase2.phase3.occupancy import (  # noqa: E402
    OGConfig, ObjectBox, compute_occupancy_utility, occupancy_gate_per_object,
    make_ctu_grid, _ctu_box_corners,
)
from phase2.phase3.og_ipf import (  # noqa: E402
    MinProtectionConfig,
    apply_min_object_protection,
    compute_og_a_plus_delta,
    compute_og_diagnostics,
    end_to_end_og_a_plus,
    min_protection_floor,
)


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------

PASSED = []
FAILED = []


def _result(label: str, ok: bool, detail: str = "") -> None:
    tag = "[PASS]" if ok else "[FAIL]"
    print(f"{tag} {label}{(' — ' + detail) if detail else ''}")
    (PASSED if ok else FAILED).append(label)


# ---------------------------------------------------------------------------
# Test 1: empty boxes → zero maps
# ---------------------------------------------------------------------------

def t01_empty_boxes() -> None:
    res = compute_occupancy_utility([], frame_h=1152, frame_w=1920,
                                     ctu_size=128)
    ok = (res.U.shape == (9, 15) and res.G_max.shape == (9, 15)
          and bool(np.allclose(res.U, 0.0))
          and bool(np.allclose(res.G_max, 0.0))
          and res.n_objects == 0)
    _result("01 empty box list → zero U, zero G_max, n_objects=0", ok,
            f"U.max={float(res.U.max()):.4f}")


# ---------------------------------------------------------------------------
# Test 2: A^obj rescues SMALL objects (the §7.20 motivation)
# ---------------------------------------------------------------------------

def t02_small_object_protection() -> None:
    """A 32×32 person inside one CTU should give that CTU G ≈ λ_obj."""
    box = ObjectBox(x=128.0 + 48.0, y=128.0 + 48.0, w=32.0, h=32.0,
                    confidence=0.9)
    cfg = OGConfig()
    n_rows, n_cols = 9, 15
    ctu_size = 128
    x1, y1, x2, y2 = _ctu_box_corners(n_rows, n_cols, ctu_size,
                                       n_rows * ctu_size, n_cols * ctu_size)
    g = occupancy_gate_per_object(box, x1, y1, x2, y2, cfg)
    # The host CTU is row=1, col=1.
    g_host = float(g[1, 1])
    # 32×32 inside a 128×128 CTU: A^ctu = 32·32/128·128 = 0.0625
    # A^obj = 1.0 (whole object inside this CTU)
    # G = 0.4·0.0625 + 0.6·1.0 = 0.625
    expected = 0.4 * (32.0 * 32.0) / (128.0 * 128.0) + 0.6 * 1.0
    ok = abs(g_host - expected) < 1e-4 and g_host > 0.5
    _result(
        "02 small (32x32) object inside one CTU → G ≈ 0.625 (saved by A^obj)",
        ok, f"G_host={g_host:.4f} expected={expected:.4f}",
    )


# ---------------------------------------------------------------------------
# Test 3: min_protection_floor is monotone in Q_b within band
# ---------------------------------------------------------------------------

def t03_min_protection_schedule() -> None:
    cfg = MinProtectionConfig()  # floor 1.0, ceil 2.2, slope 0.08
    vals = [min_protection_floor(q, cfg) for q in (27, 32, 37, 42)]
    ok = (
        abs(vals[0] - 1.0) < 1e-9
        and vals[1] > vals[0]
        and vals[2] > vals[1]
        and vals[3] <= cfg.ceil + 1e-9
        and all(cfg.floor - 1e-9 <= v <= cfg.ceil + 1e-9 for v in vals)
    )
    _result("03 δ_min schedule monotone in [1.0, 2.2] for Q_b ∈ {27..42}", ok,
            f"vals={vals}")


# ---------------------------------------------------------------------------
# Test 4: apply_min_object_protection idempotent + never raises δ
# ---------------------------------------------------------------------------

def t04_min_protect_idempotent() -> None:
    rng = np.random.default_rng(0)
    delta = rng.uniform(-3, +3, size=(9, 15))
    g_max = rng.uniform(0, 1, size=(9, 15))
    once = apply_min_object_protection(delta, g_max, q_base=32)
    twice = apply_min_object_protection(once, g_max, q_base=32)
    monotone_down = bool(np.all(once <= delta + 1e-9))
    idempotent = bool(np.allclose(once, twice))
    _result(
        "04 apply_min_object_protection: idempotent and never raises δ",
        monotone_down and idempotent,
        f"max_increase={float((once - delta).max()):.4f}",
    )


# ---------------------------------------------------------------------------
# Test 5: end-to-end OG-A+ map is rate-neutral (continuous)
# ---------------------------------------------------------------------------

def t05_rate_neutral_continuous() -> None:
    rng = np.random.default_rng(7)
    # Build a realistic utility + complexity field on a 9×15 grid:
    # ~30 % of CTUs are object-overlapping; the rest are background.
    U = rng.exponential(1.0, size=(9, 15))
    K = rng.exponential(1.0, size=(9, 15))
    G_max = np.zeros((9, 15))
    object_mask = rng.uniform(size=(9, 15)) < 0.30
    G_max[object_mask] = rng.uniform(0.4, 1.0, size=int(object_mask.sum()))
    out = end_to_end_og_a_plus(U=U, G_max=G_max, K=K, q_base=32)
    drift = abs(out.rate_ratio_continuous - 1.0)
    _result(
        "05 end_to_end_og_a_plus: continuous rate ratio ≈ 1.0 (30 % G>0)",
        drift < 1e-3,
        f"ratio_continuous={out.rate_ratio_continuous:.6f} drift={drift:.2e}",
    )


# ---------------------------------------------------------------------------
# Test 6: object_protection_violation < 5 % on the synthetic frame
# ---------------------------------------------------------------------------

def t06_protection_violation() -> None:
    rng = np.random.default_rng(11)
    U = rng.exponential(1.0, size=(9, 15))
    K = rng.exponential(1.0, size=(9, 15))
    G_max = np.zeros((9, 15))
    # Two CTUs strongly overlap an object.
    G_max[3, 5] = 0.9
    G_max[4, 6] = 0.95
    out = end_to_end_og_a_plus(U=U, G_max=G_max, K=K, q_base=32)
    diag = compute_og_diagnostics(
        delta_continuous=out.delta_continuous,
        delta_int=out.delta_int.astype(np.float64),
        G_max=G_max, K=K,
    )
    ok = diag.object_protection_violation <= 0.05
    _result(
        "06 object-protection violation ≤ 5 % when G > 0.5 CTUs are protected",
        ok, f"violation={diag.object_protection_violation:.4f}",
    )


# ---------------------------------------------------------------------------
# Test 7: ObjectBox.from_dict accepts three input shapes
# ---------------------------------------------------------------------------

def t07_objectbox_loaders() -> None:
    a = ObjectBox.from_dict({"x": 0.0, "y": 0.0, "w": 10.0, "h": 20.0,
                              "confidence": 0.5})
    b = ObjectBox.from_dict({"x_center": 5.0, "y_center": 10.0,
                              "width": 10.0, "height": 20.0})
    c = ObjectBox.from_dict({"xyxy": [0.0, 0.0, 10.0, 20.0], "score": 0.7})
    ok = (
        a.w == 10.0 and a.h == 20.0 and a.confidence == 0.5
        and b.x == 0.0 and b.y == 0.0 and b.w == 10.0 and b.h == 20.0
        and c.confidence == 0.7 and c.w == 10.0 and c.h == 20.0
    )
    _result("07 ObjectBox.from_dict accepts xywh, centred, and xyxy", ok)


# ---------------------------------------------------------------------------
# Test 8: end-to-end apply step (5 frames, 1 sequence, no YOLO)
# ---------------------------------------------------------------------------

def t08_apply_smoke() -> None:
    """Run apply_liteqp_model.py --mode og_a_plus on a fake sequence.

    We pre-generate boxes JSON, saliency .npy (unused in og_a_plus but
    required by the path validator), and a rate surrogate npz. Then we
    invoke the apply script and assert the directory layout + the
    diagnostics CSV.
    """
    with tempfile.TemporaryDirectory() as td:
        td_p = Path(td)
        sal = td_p / "sal"; sal.mkdir()
        rate_npz = td_p / "rate.npz"
        out_dir = td_p / "M4"

        ctu_rows, ctu_cols = 9, 15
        n_frames = 5
        # Synthetic per-frame K_grids and saliency.
        K = np.exp(np.random.default_rng(0).normal(0, 0.3,
                    size=(n_frames, ctu_rows, ctu_cols)))
        np.savez(rate_npz, K_grids=K)
        for fi in range(n_frames):
            np.save(sal / f"phi_oracle_{fi:06d}.npy",
                     np.random.default_rng(fi).uniform(size=(ctu_rows, ctu_cols))
                     .astype(np.float32))
            np.save(sal / f"phi_oracle_norm_{fi:06d}.npy",
                     np.random.default_rng(fi).uniform(size=(ctu_rows, ctu_cols))
                     .astype(np.float32))
            # One random "person" inside the frame for each fi.
            x1 = float(np.random.default_rng(100 + fi).uniform(0, 1700))
            y1 = float(np.random.default_rng(200 + fi).uniform(0, 1000))
            box = {"xyxy": [x1, y1, x1 + 80.0, y1 + 200.0],
                   "score": 0.9, "class": 0, "class_priority": 1.0}
            payload = {"frame_idx": fi, "frame_size": [1920, 1152],
                       "ctu_size": 128, "boxes": [box]}
            (sal / f"boxes_{fi:06d}.json").write_text(
                json.dumps(payload), encoding="utf-8")

        cmd = [
            sys.executable, "-m", "phase2.phase3.apply_liteqp_model",
            "--mode", "og_a_plus",
            "--rate-npz", str(rate_npz),
            "--saliency-dir", str(sal),
            "--boxes-dir",    str(sal),
            "--output-dir",   str(out_dir),
            "--qp-list", "27", "32", "37", "42",
            "--n-frames", str(n_frames),
            "--ctu-rows", str(ctu_rows),
            "--ctu-cols", str(ctu_cols),
            "--frame-h",  str(ctu_rows * 128),
            "--frame-w",  str(ctu_cols * 128),
            "--per-qp",
        ]
        env = {**__import__("os").environ, "PYTHONPATH": str(SRC)}
        proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if proc.returncode != 0:
            _result("08 end-to-end OG-A+ apply on 5 fake frames", False,
                     f"\nstdout:\n{proc.stdout}\nstderr:\n{proc.stderr}")
            return

        # Check directory layout.
        expected_dirs = [out_dir / f"qp_vtm_delta_QP{q}" for q in (27, 32, 37, 42)]
        all_present = all(d.is_dir() for d in expected_dirs)
        n_maps = sum(len(list(d.glob("qp_*.txt"))) for d in expected_dirs)
        meta_ok = (out_dir / "liteqp_metadata.json").exists()
        csv_ok  = (out_dir / "og_diagnostics_summary.csv").exists()
        ok = all_present and n_maps == 4 * n_frames and meta_ok and csv_ok
        _result(
            "08 end-to-end OG-A+ apply on 5 fake frames",
            ok,
            f"dirs={all_present} n_maps={n_maps}/{4 * n_frames} "
            f"meta={meta_ok} csv={csv_ok}",
        )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    t01_empty_boxes()
    t02_small_object_protection()
    t03_min_protection_schedule()
    t04_min_protect_idempotent()
    t05_rate_neutral_continuous()
    t06_protection_violation()
    t07_objectbox_loaders()
    t08_apply_smoke()
    print()
    print(f"PASSED: {len(PASSED)} / {len(PASSED) + len(FAILED)}")
    return 0 if not FAILED else 1


if __name__ == "__main__":
    sys.exit(main())
