"""Offline sanity check for the OG-IPF stack (PROJECT_STATE §7.20).

Runs without GPU, without VTM, without YOLO. The tests cover the
mathematical invariants of the new method:

1. ``occupancy.compute_occupancy_utility`` reduces to zero when there
   are no boxes, and to a sane scalar field when there is one big box.
2. ``A^obj`` correctly emphasises **small** objects (the central
   failure mode the OG-IPF is meant to fix).
3. ``min_protection_floor`` schedules δ_min monotonically over Q_b
   inside the [floor, ceil] band.
4. ``apply_min_object_protection`` is idempotent and never *raises*
   δ for any CTU (it can only push it down).
5. ``end_to_end_og_a_plus`` produces a continuous map whose
   K-weighted rate ratio is ≈ 1.0 (rate-neutral by construction).
6. ``compute_og_diagnostics`` reports ``object_protection_violation
   ≤ 5 %`` on a synthetic frame where the constraint is met.
7. ``ObjectBox.from_dict`` accepts all three legitimate dict shapes
   (Phase 1 ObjectState, simple ``{x, y, w, h}``, and YOLO ``xyxy``).
8. End-to-end smoke: ``apply_liteqp_model --mode og_a_plus`` produces
   ``qp_vtm_delta_QP{n}/`` with one map per (QP, frame) and writes
   a non-empty ``og_diagnostics_summary.csv`` for a 5-frame fake
   sequence (needs no YOLO — boxes JSON files are pre-generated by
   the test).

Run::

    PYTHONPATH=src python scripts/sanity_check_og_ipf.py

Exit 0 on success.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except AttributeError:
    pass

HERE = Path(__file__).resolve().parents[1]
SRC  = HERE / "src"
sys.path.insert(0, str(SRC))

import numpy as np  # noqa: E402  (after sys.path manipulation)

from phase2.phase3.occupancy import (  # noqa: E402
    OGConfig, ObjectBox, compute_occupancy_utility, occupancy_gate_per_object,
    make_ctu_grid, _ctu_box_corners,
)
from phase2.phase3.og_ipf import (  # noqa: E402
    MinProtectionConfig,
    apply_min_object_protection,
    compute_og_a_plus_delta,
    compute_og_diagnostics,
    end_to_end_og_a_plus,
    min_protection_floor,
    protection_activation,
)


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------

PASSED = []
FAILED = []


def _result(label: str, ok: bool, detail: str = "") -> None:
    tag = "[PASS]" if ok else "[FAIL]"
    print(f"{tag} {label}{(' — ' + detail) if detail else ''}")
    (PASSED if ok else FAILED).append(label)


# ---------------------------------------------------------------------------
# Test 1: empty boxes → zero maps
# ---------------------------------------------------------------------------

def t01_empty_boxes() -> None:
    res = compute_occupancy_utility([], frame_h=1152, frame_w=1920,
                                     ctu_size=128)
    ok = (res.U.shape == (9, 15) and res.G_max.shape == (9, 15)
          and bool(np.allclose(res.U, 0.0))
          and bool(np.allclose(res.G_max, 0.0))
          and res.n_objects == 0)
    _result("01 empty box list → zero U, zero G_max, n_objects=0", ok,
            f"U.max={float(res.U.max()):.4f}")


# ---------------------------------------------------------------------------
# Test 2: A^obj rescues SMALL objects (the §7.20 motivation)
# ---------------------------------------------------------------------------

def t02_small_object_protection() -> None:
    """A 32×32 person inside one CTU should give that CTU G ≈ λ_obj."""
    box = ObjectBox(x=128.0 + 48.0, y=128.0 + 48.0, w=32.0, h=32.0,
                    confidence=0.9)
    cfg = OGConfig()
    n_rows, n_cols = 9, 15
    ctu_size = 128
    x1, y1, x2, y2 = _ctu_box_corners(n_rows, n_cols, ctu_size,
                                       n_rows * ctu_size, n_cols * ctu_size)
    g = occupancy_gate_per_object(box, x1, y1, x2, y2, cfg)
    # The host CTU is row=1, col=1.
    g_host = float(g[1, 1])
    # 32×32 inside a 128×128 CTU: A^ctu = 32·32/128·128 = 0.0625
    # A^obj = 1.0 (whole object inside this CTU)
    # G = 0.4·0.0625 + 0.6·1.0 = 0.625
    expected = 0.4 * (32.0 * 32.0) / (128.0 * 128.0) + 0.6 * 1.0
    ok = abs(g_host - expected) < 1e-4 and g_host > 0.5
    _result(
        "02 small (32x32) object inside one CTU → G ≈ 0.625 (saved by A^obj)",
        ok, f"G_host={g_host:.4f} expected={expected:.4f}",
    )


# ---------------------------------------------------------------------------
# Test 3: min_protection_floor is monotone in Q_b within band
# ---------------------------------------------------------------------------

def t03_min_protection_schedule() -> None:
    cfg = MinProtectionConfig()  # floor 1.0, ceil 2.2, slope 0.08
    vals = [min_protection_floor(q, cfg) for q in (27, 32, 37, 42)]
    ok = (
        abs(vals[0] - 1.0) < 1e-9
        and vals[1] > vals[0]
        and vals[2] > vals[1]
        and vals[3] <= cfg.ceil + 1e-9
        and all(cfg.floor - 1e-9 <= v <= cfg.ceil + 1e-9 for v in vals)
    )
    _result("03 δ_min schedule monotone in [1.0, 2.2] for Q_b ∈ {27..42}", ok,
            f"vals={vals}")


# ---------------------------------------------------------------------------
# Test 4: apply_min_object_protection idempotent + never raises δ
# ---------------------------------------------------------------------------

def t04_min_protect_idempotent() -> None:
    rng = np.random.default_rng(0)
    delta = rng.uniform(-3, +3, size=(9, 15))
    g_max = rng.uniform(0, 1, size=(9, 15))
    once = apply_min_object_protection(delta, g_max, q_base=32)
    twice = apply_min_object_protection(once, g_max, q_base=32)
    monotone_down = bool(np.all(once <= delta + 1e-9))
    idempotent = bool(np.allclose(once, twice))
    _result(
        "04 apply_min_object_protection: idempotent and never raises δ",
        monotone_down and idempotent,
        f"max_increase={float((once - delta).max()):.4f}",
    )


# ---------------------------------------------------------------------------
# Test 5: end-to-end OG-A+ map is rate-neutral (continuous)
# ---------------------------------------------------------------------------

def t05_rate_neutral_continuous() -> None:
    rng = np.random.default_rng(7)
    # Build a realistic utility + complexity field on a 9×15 grid:
    # ~30 % of CTUs are object-overlapping; the rest are background.
    U = rng.exponential(1.0, size=(9, 15))
    K = rng.exponential(1.0, size=(9, 15))
    G_max = np.zeros((9, 15))
    object_mask = rng.uniform(size=(9, 15)) < 0.30
    G_max[object_mask] = rng.uniform(0.4, 1.0, size=int(object_mask.sum()))
    out = end_to_end_og_a_plus(U=U, G_max=G_max, K=K, q_base=32)
    drift = abs(out.rate_ratio_continuous - 1.0)
    _result(
        "05 end_to_end_og_a_plus: continuous rate ratio ≈ 1.0 (30 % G>0)",
        drift < 1e-3,
        f"ratio_continuous={out.rate_ratio_continuous:.6f} drift={drift:.2e}",
    )


# ---------------------------------------------------------------------------
# Test 6: object_protection_violation < 5 % on the synthetic frame
# ---------------------------------------------------------------------------

def t06_protection_violation() -> None:
    """At QP=42 activation=1.0, protected CTUs must have δ < 0."""
    rng = np.random.default_rng(11)
    U = rng.exponential(1.0, size=(9, 15))
    K = rng.exponential(1.0, size=(9, 15))
    G_max = np.zeros((9, 15))
    # Two CTUs strongly overlap an object.
    G_max[3, 5] = 0.9
    G_max[4, 6] = 0.95
    # Use q_base=42 where activation=1.0 so protection is fully active.
    out = end_to_end_og_a_plus(U=U, G_max=G_max, K=K, q_base=42)
    diag = compute_og_diagnostics(
        delta_continuous=out.delta_continuous,
        delta_int=out.delta_int.astype(np.float64),
        G_max=G_max, K=K,
        activation_factor=out.activation_factor,
    )
    ok = diag.object_protection_violation <= 0.05
    _result(
        "06 object-protection violation ≤ 5 % when G > 0.5 CTUs are protected "
        "(QP=42, activation=1.0)",
        ok, f"violation={diag.object_protection_violation:.4f} "
            f"act={out.activation_factor:.2f}",
    )


# ---------------------------------------------------------------------------
# Test 7: ObjectBox.from_dict accepts three input shapes
# ---------------------------------------------------------------------------

def t07_objectbox_loaders() -> None:
    a = ObjectBox.from_dict({"x": 0.0, "y": 0.0, "w": 10.0, "h": 20.0,
                              "confidence": 0.5})
    b = ObjectBox.from_dict({"x_center": 5.0, "y_center": 10.0,
                              "width": 10.0, "height": 20.0})
    c = ObjectBox.from_dict({"xyxy": [0.0, 0.0, 10.0, 20.0], "score": 0.7})
    ok = (
        a.w == 10.0 and a.h == 20.0 and a.confidence == 0.5
        and b.x == 0.0 and b.y == 0.0 and b.w == 10.0 and b.h == 20.0
        and c.confidence == 0.7 and c.w == 10.0 and c.h == 20.0
    )
    _result("07 ObjectBox.from_dict accepts xywh, centred, and xyxy", ok)


# ---------------------------------------------------------------------------
# Test 8: end-to-end apply step (5 frames, 1 sequence, no YOLO)
# ---------------------------------------------------------------------------

def t08_apply_smoke() -> None:
    """Run apply_liteqp_model.py --mode og_a_plus on a fake sequence.

    We pre-generate boxes JSON, saliency .npy (unused in og_a_plus but
    required by the path validator), and a rate surrogate npz. Then we
    invoke the apply script and assert the directory layout + the
    diagnostics CSV.

    The boxes are pinned to a **deterministic** location and large
    enough that several CTUs end up with G_c > 0.5 every frame. This
    way, ``object_protection_violation`` is a meaningful number (the
    bug discovered in pilot_v6_og — violation_max ≈ 1.0 for a
    sequence with too few overlap CTUs — was hidden by the previous
    randomised-tiny-bbox fixture).
    """
    with tempfile.TemporaryDirectory() as td:
        td_p = Path(td)
        sal = td_p / "sal"; sal.mkdir()
        rate_npz = td_p / "rate.npz"
        out_dir = td_p / "M4"

        ctu_rows, ctu_cols = 9, 15
        n_frames = 5
        # Synthetic per-frame K_grids and saliency.
        K = np.exp(np.random.default_rng(0).normal(0, 0.3,
                    size=(n_frames, ctu_rows, ctu_cols)))
        np.savez(rate_npz, K_grids=K)
        for fi in range(n_frames):
            np.save(sal / f"phi_oracle_{fi:06d}.npy",
                     np.random.default_rng(fi).uniform(size=(ctu_rows, ctu_cols))
                     .astype(np.float32))
            np.save(sal / f"phi_oracle_norm_{fi:06d}.npy",
                     np.random.default_rng(fi).uniform(size=(ctu_rows, ctu_cols))
                     .astype(np.float32))
            # **Deterministic**, large box that fully overlaps several
            # CTUs. We place it at row 3-4, col 5-7 with size 256x384
            # so ~6 CTUs see G > 0.5 every frame (a regression-stable
            # number that catches the violation_max bug).
            box = {"xyxy": [640.0, 384.0, 1024.0, 640.0],
                   "score": 0.9, "class": 0, "class_priority": 1.0}
            payload = {"frame_idx": fi, "frame_size": [1920, 1152],
                       "ctu_size": 128, "boxes": [box]}
            (sal / f"boxes_{fi:06d}.json").write_text(
                json.dumps(payload), encoding="utf-8")

        cmd = [
            sys.executable, "-m", "phase2.phase3.apply_liteqp_model",
            "--mode", "og_a_plus",
            "--rate-npz",   str(rate_npz),
            "--saliency-dir", str(sal),
            "--boxes-dir",  str(sal),
            "--output-dir", str(out_dir),
            "--qp-list", "27", "32", "37", "42",
            "--n-frames", str(n_frames),
            "--ctu-rows", str(ctu_rows),
            "--ctu-cols", str(ctu_cols),
            "--frame-h",   str(ctu_rows * 128),   # padded: 1152
            "--frame-w",   str(ctu_cols * 128),   # padded: 1920
            "--visible-h", str(ctu_rows * 128 - 72),  # 1080 (simulates real MOT17)
            "--visible-w", str(ctu_cols * 128),
            "--per-qp",
        ]
        env = {**__import__("os").environ, "PYTHONPATH": str(SRC)}
        proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if proc.returncode != 0:
            _result("08 end-to-end OG-A+ apply on 5 fake frames", False,
                     f"\nstdout:\n{proc.stdout}\nstderr:\n{proc.stderr}")
            return

        # Check directory layout.
        expected_dirs = [out_dir / f"qp_vtm_delta_QP{q}" for q in (27, 32, 37, 42)]
        all_present = all(d.is_dir() for d in expected_dirs)
        n_maps = sum(len(list(d.glob("qp_*.txt"))) for d in expected_dirs)
        meta_ok = (out_dir / "liteqp_metadata.json").exists()
        csv_ok  = (out_dir / "og_diagnostics_summary.csv").exists()
        ok = all_present and n_maps == 4 * n_frames and meta_ok and csv_ok
        _result(
            "08 end-to-end OG-A+ apply on 5 fake frames",
            ok,
            f"dirs={all_present} n_maps={n_maps}/{4 * n_frames} "
            f"meta={meta_ok} csv={csv_ok}",
        )

        # ── Test 09 (regression): real CSV must show violation < 5 % and
        #    rate-ratio drift < 5 % for every QP. This is the invariant
        #    that pilot_v6_og violated due to scalar-bounded projection.
        if not csv_ok:
            return
        import csv as _csv
        worst_violation = 0.0
        worst_drift     = 0.0
        rows_seen       = 0
        with open(out_dir / "og_diagnostics_summary.csv",
                   "r", encoding="utf-8") as f:
            reader = _csv.DictReader(f)
            for row in reader:
                rows_seen += 1
                worst_violation = max(
                    worst_violation,
                    float(row["object_protection_violation_max"]),
                )
                worst_drift = max(
                    worst_drift,
                    abs(float(row["mean_rate_ratio_rounded"]) - 1.0),
                )
        _result(
            "09 OG apply CSV: object_protection_violation_max < 5 % "
            "AND |rate_ratio_rounded - 1| < 5 % every QP "
            "(regression for pilot_v6_og bug)",
            rows_seen >= 4
                and worst_violation < 0.05
                and worst_drift < 0.05,
            f"rows={rows_seen} worst_violation={worst_violation:.4f} "
            f"worst_drift={worst_drift:.4f}",
        )


# ---------------------------------------------------------------------------
# Test 10: protection_activation schedule
# ---------------------------------------------------------------------------

def t10_activation_schedule() -> None:
    """Default config: QP=27/32 → 0.0, QP=37 → 0.5, QP=42 → 1.0."""
    cfg = MinProtectionConfig()  # activation_q0=32, activation_q1=42
    a27 = protection_activation(27, cfg)
    a32 = protection_activation(32, cfg)
    a37 = protection_activation(37, cfg)
    a42 = protection_activation(42, cfg)
    ok = (
        abs(a27 - 0.0) < 1e-9
        and abs(a32 - 0.0) < 1e-9
        and abs(a37 - 0.5) < 1e-9
        and abs(a42 - 1.0) < 1e-9
    )
    _result(
        "10 protection_activation: QP27=0, QP32=0, QP37=0.5, QP42=1",
        ok, f"a27={a27:.4f} a32={a32:.4f} a37={a37:.4f} a42={a42:.4f}",
    )


# ---------------------------------------------------------------------------
# Test 11: padded 1152 / visible 1080 CTU geometry
# ---------------------------------------------------------------------------

def t11_padded_visible_ctu_dims() -> None:
    """1152-padded / 1080-visible: 9 CTU rows, bottom row visible height = 56 px.

    Row 8 (0-indexed) spans pixels [1024, 1152) in the padded grid, but
    the visible clip is 1080, so its effective visible height is 56 pixels.
    """
    from phase2.phase3.occupancy import make_ctu_grid, _ctu_box_corners

    frame_h, visible_h = 1152, 1080
    frame_w, visible_w = 1920, 1920
    ctu_size = 128

    _, _, n_rows, n_cols = make_ctu_grid(frame_h, frame_w, ctu_size)
    # Corners clipped to PADDED dims (old behaviour)
    x1p, y1p, x2p, y2p = _ctu_box_corners(
        n_rows, n_cols, ctu_size, frame_h, frame_w)
    # Corners clipped to VISIBLE dims (new behaviour via visible_h)
    x1v, y1v, x2v, y2v = _ctu_box_corners(
        n_rows, n_cols, ctu_size, visible_h, visible_w)

    ok_rows = (n_rows == 9)
    # Bottom-row padded height  = 1152 - 1024 = 128 (full CTU)
    # Bottom-row visible height = 1080 - 1024 = 56
    bottom_h_padded  = float(y2p[8, 0] - y1p[8, 0])
    bottom_h_visible = float(y2v[8, 0] - y1v[8, 0])
    ok_pad = abs(bottom_h_padded  - 128.0) < 1e-6
    ok_vis = abs(bottom_h_visible -  56.0) < 1e-6

    # compute_occupancy_utility with visible_h should use 56-px last row
    box = ObjectBox(x=0.0, y=1024.0, w=100.0, h=56.0)  # sits in row 8
    from phase2.phase3.occupancy import compute_occupancy_utility
    res_pad = compute_occupancy_utility([box], frame_h=frame_h, frame_w=frame_w)
    res_vis = compute_occupancy_utility([box], frame_h=frame_h, frame_w=frame_w,
                                        visible_h=visible_h, visible_w=visible_w)
    # With padded dims CTU-8 area = 128×128 → A^ctu = 100*56/(128*128) ≈ 0.034
    # With visible dims CTU-8 area = 56×128  → A^ctu = 100*56/(56*128) ≈ 0.781
    # So G should be strictly higher in the visible case.
    g_pad = float(res_pad.G_max[8, 0])
    g_vis = float(res_vis.G_max[8, 0])
    ok_g = g_vis > g_pad + 0.1  # visible_h gives meaningfully higher occupancy

    ok = ok_rows and ok_pad and ok_vis and ok_g
    _result(
        "11 padded 1152 / visible 1080: 9 rows, bottom-row h_vis=56, "
        "G_vis > G_pad at boundary CTU",
        ok,
        f"n_rows={n_rows} h_pad={bottom_h_padded:.0f} h_vis={bottom_h_visible:.0f} "
        f"G_pad={g_pad:.4f} G_vis={g_vis:.4f}",
    )


# ---------------------------------------------------------------------------
# Test 12: og_a_plus smoke uses end_to_end_og_a_plus path
#          (activation_factor appears in the diagnostics CSV)
# ---------------------------------------------------------------------------

def t12_og_a_plus_uses_e2e_path() -> None:
    """Verify the apply script records activation_factor for og_a_plus.

    We run a 5-frame og_a_plus smoke with QP=42 (activation=1.0) and
    QP=27 (activation=0.0). The mean_activation_factor column in the
    diagnostics CSV must equal 1.0 at QP=42 and 0.0 at QP=27 (default
    schedule). If the column is absent or wrong, the script was NOT
    using end_to_end_og_a_plus().
    """
    with tempfile.TemporaryDirectory() as td:
        td_p = Path(td)
        sal = td_p / "sal"; sal.mkdir()
        rate_npz = td_p / "rate.npz"
        out_dir  = td_p / "M4"

        ctu_rows, ctu_cols = 9, 15
        n_frames = 5
        K = np.exp(np.random.default_rng(99).normal(
            0, 0.3, size=(n_frames, ctu_rows, ctu_cols)))
        np.savez(rate_npz, K_grids=K)
        for fi in range(n_frames):
            np.save(sal / f"phi_oracle_{fi:06d}.npy",
                     np.random.default_rng(fi).uniform(
                         size=(ctu_rows, ctu_cols)).astype(np.float32))
            box = {"xyxy": [640.0, 384.0, 1024.0, 640.0],
                   "score": 0.9, "class": 0, "class_priority": 1.0}
            payload = {"frame_idx": fi, "boxes": [box]}
            (sal / f"boxes_{fi:06d}.json").write_text(
                json.dumps(payload), encoding="utf-8")

        cmd = [
            sys.executable, "-m", "phase2.phase3.apply_liteqp_model",
            "--mode", "og_a_plus",
            "--rate-npz",   str(rate_npz),
            "--saliency-dir", str(sal),
            "--boxes-dir",  str(sal),
            "--output-dir", str(out_dir),
            "--qp-list", "27", "42",
            "--n-frames", str(n_frames),
            "--ctu-rows", str(ctu_rows),
            "--ctu-cols", str(ctu_cols),
            "--frame-h",  str(ctu_rows * 128),
            "--frame-w",  str(ctu_cols * 128),
            "--visible-h", "1080",
            "--visible-w", "1920",
            "--og-activation-q0", "32.0",
            "--og-activation-q1", "42.0",
            "--og-activation-min", "0.0",
            "--og-activation-max", "1.0",
            "--per-qp",
        ]
        env = {**__import__("os").environ, "PYTHONPATH": str(SRC)}
        proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if proc.returncode != 0:
            _result("12 og_a_plus uses end_to_end path (activation_factor in CSV)",
                     False, f"script failed:\n{proc.stderr[-800:]}")
            return

        csv_path = out_dir / "og_diagnostics_summary.csv"
        if not csv_path.exists():
            _result("12 og_a_plus uses end_to_end path (activation_factor in CSV)",
                     False, "CSV not written")
            return

        import csv as _csv
        act_by_qp: dict[int, float] = {}
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = _csv.DictReader(f)
            if "mean_activation_factor" not in (reader.fieldnames or []):
                _result("12 og_a_plus uses end_to_end path (activation_factor in CSV)",
                         False, "column mean_activation_factor absent from CSV")
                return
            for row in reader:
                qp_v = int(row["qp_base"])
                act_by_qp[qp_v] = float(row["mean_activation_factor"])

        act27 = act_by_qp.get(27, -1.0)
        act42 = act_by_qp.get(42, -1.0)
        ok = abs(act27 - 0.0) < 1e-6 and abs(act42 - 1.0) < 1e-6
        _result(
            "12 og_a_plus uses end_to_end path (activation_factor in CSV)",
            ok,
            f"act@QP27={act27:.4f} (expect 0.0), act@QP42={act42:.4f} (expect 1.0)",
        )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    t01_empty_boxes()
    t02_small_object_protection()
    t03_min_protection_schedule()
    t04_min_protect_idempotent()
    t05_rate_neutral_continuous()
    t06_protection_violation()
    t07_objectbox_loaders()
    t08_apply_smoke()
    t10_activation_schedule()
    t11_padded_visible_ctu_dims()
    t12_og_a_plus_uses_e2e_path()
    print()
    print(f"PASSED: {len(PASSED)} / {len(PASSED) + len(FAILED)}")
    return 0 if not FAILED else 1


if __name__ == "__main__":
    sys.exit(main())
