/**
 * @file external_qp_reader.h
 * @brief Reads per-CTU QP maps from external text files for ROI-aware encoding.
 *
 * This is a standalone helper added to VTM for the IPF (Importance Potential
 * Field) project. It reads QP map files generated by the Phase 1 pipeline
 * and provides per-CTU QP values to the encoder.
 *
 * File format (produced by phase1/export/qp_exporter.py):
 *   # frame=<idx> rows=<nr> cols=<nc>
 *   qp_00 qp_01 ... qp_0(nc-1)
 *   qp_10 qp_11 ... qp_1(nc-1)
 *   ...
 *
 * Usage in VTM:
 *   ExternalQPReader reader("/path/to/qp_maps/");
 *   if (reader.isEnabled()) {
 *       int qp = reader.getQP(frameIdx, ctuRow, ctuCol);
 *       // Use qp for this CTU
 *   }
 */

#ifndef EXTERNAL_QP_READER_H
#define EXTERNAL_QP_READER_H

#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <map>

class ExternalQPReader
{
private:
  std::string m_qpMapDir;
  bool        m_enabled;

  struct QPMap
  {
    int                          numRows;
    int                          numCols;
    std::vector<std::vector<int>> data;
  };

  std::map<int, QPMap> m_cache;

  QPMap loadFrame(int frameIdx)
  {
    QPMap map;
    map.numRows = 0;
    map.numCols = 0;

    std::ostringstream fname;
    fname << m_qpMapDir << "/qp_" << std::setw(6) << std::setfill('0') << frameIdx << ".txt";

    std::ifstream ifs(fname.str());
    if (!ifs.is_open())
    {
      std::cerr << "ExternalQPReader: WARNING - Could not open " << fname.str() << std::endl;
      return map;
    }

    std::string line;
    while (std::getline(ifs, line))
    {
      if (line.empty() || line[0] == '#')
      {
        if (line.find("rows=") != std::string::npos)
        {
          size_t rpos = line.find("rows=");
          size_t cpos = line.find("cols=");
          if (rpos != std::string::npos)
          {
            map.numRows = std::stoi(line.substr(rpos + 5));
          }
          if (cpos != std::string::npos)
          {
            map.numCols = std::stoi(line.substr(cpos + 5));
          }
        }
        continue;
      }

      std::vector<int>  row;
      std::istringstream iss(line);
      int                val;
      while (iss >> val)
      {
        row.push_back(val);
      }
      if (!row.empty())
      {
        map.data.push_back(row);
      }
    }

    if (map.numRows == 0)
    {
      map.numRows = (int) map.data.size();
    }
    if (map.numCols == 0 && !map.data.empty())
    {
      map.numCols = (int) map.data[0].size();
    }

    return map;
  }

public:
  ExternalQPReader() : m_enabled(false) {}

  ExternalQPReader(const std::string& qpMapDir) : m_qpMapDir(qpMapDir), m_enabled(false)
  {
    if (!qpMapDir.empty())
    {
      m_enabled = true;
      std::cout << "ExternalQPReader: Enabled, reading from " << qpMapDir << std::endl;
    }
  }

  bool isEnabled() const { return m_enabled; }

  void setDir(const std::string& dir)
  {
    m_qpMapDir = dir;
    m_enabled  = !dir.empty();
  }

  /**
   * Get the QP value for a specific CTU position in a specific frame.
   *
   * @param frameIdx  Frame index (0-based, encoding order)
   * @param ctuRow    CTU row index (0-based)
   * @param ctuCol    CTU column index (0-based)
   * @param defaultQP Fallback QP if map is unavailable
   * @return          QP value for this CTU
   */
  int getQP(int frameIdx, int ctuRow, int ctuCol, int defaultQP)
  {
    if (!m_enabled)
    {
      return defaultQP;
    }

    auto it = m_cache.find(frameIdx);
    if (it == m_cache.end())
    {
      m_cache[frameIdx] = loadFrame(frameIdx);
      it                = m_cache.find(frameIdx);

      // Evict old frames to bound memory (keep last 4 frames for B-frame reordering)
      if (m_cache.size() > 8)
      {
        auto oldest = m_cache.begin();
        if (oldest->first < frameIdx - 4)
        {
          m_cache.erase(oldest);
        }
      }
    }

    const QPMap& map = it->second;
    if (map.data.empty())
    {
      return defaultQP;
    }

    if (ctuRow < 0 || ctuRow >= (int) map.data.size())
    {
      return defaultQP;
    }
    if (ctuCol < 0 || ctuCol >= (int) map.data[ctuRow].size())
    {
      return defaultQP;
    }

    int qp = map.data[ctuRow][ctuCol];

    // Clamp to valid VVC QP range
    if (qp < 0)
      qp = 0;
    if (qp > 63)
      qp = 63;

    return qp;
  }

  /**
   * Clear the frame cache. Call between encoding passes if needed.
   */
  void clearCache() { m_cache.clear(); }
};

#endif // EXTERNAL_QP_READER_H
